plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

android {
    namespace 'com.jichi.ob'
    compileSdk 36

    defaultConfig {
        applicationId "com.jichi.ob.dev"
        minSdk 26
        targetSdk 36
        versionCode 642
        versionName "6.3.12"
    }

    buildFeatures {
        buildConfig true
    }

    signingConfigs {
        release {
            storeFile file('../jichi-ob-dev.keystore')
            storePassword 'jichiobdev2026'
            keyAlias 'jichiobdev'
            keyPassword 'jichiobdev2026'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = '17'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.lifecycle:lifecycle-runtime-ktx:2.7.0'
    implementation 'com.squareup.okhttp3:okhttp:4.12.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
